### ISSUE TITLE
Only the background colour is coming  but not the first  charecter  of user name.

### ISSUE THREAD

**Issue by krishnarout** [mumairofficial/text-avatar#11]

**Comment by krishnarout** [comment]
Here is my app.ts code 
import {Component} from '@angular/core';
import {
  IonicPage,
  ModalController,
  NavController,
  NavParams,
  ToastController,
  AlertController,
  LoadingController
} from 'ionic-angular';
import {Vibration} from '@ionic-native/vibration';


import {Item} from '../../models/item';
import {Items} from '../../providers';
import {ItemSliding} from "ionic-angular/umd";


@IonicPage()
@Component({
  selector: 'users_lists',
  templateUrl: 'users_lists.html'
})
export class UsersPage {

  currentItems: any[];
  public press: number = 0;

  public users: any[] = [
    { name: "Abdul Basit", company: "Siemens", job_title: "Technical Lead", color: '#ccc' },
    { name: "Amin Ullah", company: "NBS", job_title: "BI Engineer" },
    { name: "Haris Altaf", company: "Siemens", job_title: "Technical Lead" },
    { name: "Muhammad Umair", company: "Siemens", job_title: "Software Engineer" },
    { name: "Talal", company: "Siemens", job_title: "Software Engineer" },
    { name: "Usman Iftkhar", company: "Siemens", job_title: "Sr. Technical Lead" },
    { name: "Umar Hayat", company: "NBS", job_title: "Software Engineer" }];



  constructor(public vibration: Vibration, public navCtrl: NavController, public navParams: NavParams,
              public items: Items, public modalCtrl: ModalController,
              public toastCtrl: ToastController, private alertCtrl: AlertController,
              public loadingCtrl: LoadingController) {

    // this.currentItems = this.items.query();


  }
  public presentUserInfoAlert(user: any): void {
    console.log(JSON.stringify(user));
  }
  and here is my app.html code snippet

 <ion-list>
      <button ion-item *ngFor="let user of users" (click)="presentUserInfoAlert(user)">
        <text-avatar [text]="user.name" [color]="user.color" item-left></text-avatar>
        <h2>{{ user.name || upper}}</h2>
        <p>{{ user.company }} - {{ user.job_title }}</p>
      </button>
      
      
  
      
    </ion-list>

**Comment by mumairofficial** [comment]
Hi @krishnarout 

I did not see if you have used `text-avatar` directive into your code! 

> <text-avatar [text]="user.name" [color]="user.color" item-left></text-avatar>

I would suggest you to follow steps mentioned in [README](https://github.com/mumairofficial/text-avatar/blob/master/README.md) file. 

If problem persists then kindly share exact code snippet.

**Comment by krishnarout** [comment]
here is the html code:
  <ion-list>
      <button ion-item *ngFor="let user of users" (click)="presentUserInfoAlert(user)">
        <text-avatar [text]="user.name" [color]="user.color" item-left></text-avatar>
        <h2>{{ user.name || upper}}</h2>
        <p>{{ user.company }} - {{ user.job_title }}</p>
      </button>
    </ion-list>

**Comment by krishnarout** [comment]
<ion-list>
      <button ion-item *ngFor="let user of users" (click)="presentUserInfoAlert(user)">
        <text-avatar [text]="user.name" [color]="user.color" item-left></text-avatar>
        
      </button>
    </ion-list>
html code snippet

**Comment by krishnarout** [comment]
> Hi @krishnarout
> 
> I did not see if you have used `text-avatar` directive into your code!
> 
> > <text-avatar [text]="user.name" [color]="user.color" item-left>
> 
> I would suggest you to follow steps mentioned in [README](https://github.com/mumairofficial/text-avatar/blob/master/README.md) file.
> 
> If problem persists then kindly share exact code snippet.

Yes I am using the directive but while trying to paste in comment section its not taking. But I am using the directives.

**Comment by mumairofficial** [comment]
@krishnarout Can you share package.json file content. I want to see versions to reproduce this issue

**Comment by krishnarout** [comment]
Here is my package.json please check

**Comment by mumairofficial** [comment]
I did not see the content. Can you try again!

**Comment by krishnarout** [comment]
{
  "name": "Ionic3-Multi-Purpose-Theme",
  "version": "1.0.0",
  "author": "NetTantra",
  "homepage": "https://nettantra.com/",
  "private": true,
  "scripts": {
    "start": "ionic-app-scripts serve",
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/camera": "4.3.3",
    "@ionic-native/core": "^4.11.0",
    "@ionic-native/splash-screen": "~4.11.0",
    "@ionic-native/status-bar": "~4.11.0",
    "@ionic-native/vibration": "^4.12.0",
    "@ionic/pro": "2.0.3",
    "@ionic/storage": "2.1.3",
    "@ngx-translate/core": "8.0.0",
    "@ngx-translate/http-loader": "^2.0.0",
    "cordova-android": "7.1.1",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.1.2",
    "cordova-plugin-ionic-webview": "^2.0.2",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-vibration": "^3.1.0",
    "cordova-plugin-whitelist": "^1.3.3",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.11",
    "@ionic/lab": "1.0.6",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-vibration": {}
    },
    "platforms": [
      "android"
    ]
  }
}

**Comment by krishnarout** [comment]
Hi,Any version incompatibility is there?

**Comment by mumairofficial** [comment]
I will look into this later today; if you have any fix or suggestion then PR is welcome :)

**Comment by krishnarout** [comment]
> I will look into this later today; if you have any fix or suggestion then PR is welcome :)

Any solution did you get?

**Comment by krishnarout** [comment]
Hi, the text is coming but why the background colour is not coming according to the colour-generator.ts?please help me its urgent.

**Comment by mumairofficial** [comment]
Fixed with latest version
