### ISSUE TITLE
Sass Error

### ISSUE THREAD

**Issue by 7NT** [mumairofficial/text-avatar#4]
Sass Error
`Undefined variable: "$item-ios-avatar-border-radius".`

**Comment by mumairofficial** [comment]
It seems like you are using Ionic version 3.1.0 or earlier.

In order to fix that you have to added following Sass-Variables in app.scss

```scss
$item-ios-avatar-border-radius:          50% !default;
$item-md-avatar-border-radius:           50% !default;
$item-wp-avatar-border-radius:           50% !default;
```

**Comment by mumairofficial** [comment]
I hope above solution resolved the issue, I am closing this issue.

**Comment by 7NT** [comment]
oh yes, thanks you
