### ISSUE TITLE
facing issue on --prod mode

### ISSUE THREAD

**Issue by usuf16** [mumairofficial/text-avatar#8]
typescript error
            Type TextAvatarDirective in
            C:/Users/../src/directives/text-avatar/text-avatar.ts is
            part of the declarations of 2 modules: AppModule in
            C:/Users/../src/app/app.module.ts and DirectivesModule in
            C:/Users/../src/directives/directives.module.ts! Please
            consider moving TextAvatarDirective in
            C:/Users/../src/directives/text-avatar/text-avatar.ts to a
            higher module that imports AppModule in
            C:/Users/../src/app/app.module.ts and DirectivesModule in
            C:/Users../src/directives/directives.module.ts. You can
            also create a new NgModule that exports and includes TextAvatarDirective in
            C:/Users/../src/directives/text-avatar/text-avatar.ts then
            import that NgModule in AppModule in
            C:/Users/../src/app/app.module.ts and DirectivesModule in
            C:/Users/../src/directives/directives.module.ts.

**Comment by mumairofficial** [comment]
If I get it correctly you have added **TextAvatarDirective** directive into two following modules:

1- AppModule in `/src/app/app.module.ts`
2- DirectivesModule in `/src/directives/directives.module.ts`

which is wrong; Framework did not allow us to do that. 

To fix you have to remove it (**TextAvatarDirective**) from single place; mentioned above.

Hopefully this will resolve your problem.

**Comment by mumairofficial** [comment]
Closing this issue due to its age... if same thing happen again feel free to comment
